FROM alpine:3.5
ENTRYPOINT ["/bin/run-registrator.sh"]

RUN mkdir /logs
ENV GOPATH /go
COPY ./run-registrator.sh /bin
RUN chmod 755 /bin/run-registrator.sh
RUN apk --no-cache add build-base go coreutils git ca-certificates bash
COPY . /go/src/github.com/gliderlabs/registrator
RUN cd /go/src/github.com/gliderlabs/registrator \
  && git config --global http.https://gopkg.in.followRedirects true \
	&& go get \
	&& go build -ldflags "-X main.Version=dev" -o /bin/registrator
