environment: sidecartest
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","eureka://registrator-testing.thorhudl.com:8080/eureka/v2", "2>&1", "|", "tee", "-a", "/logs/registrator-$HOSTNAME.log"]
    preferences:
      ecsCluster: t-marvel-perftest-orch
