environment: prod
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","-cleanup","-resync","300","eureka://eureka.app.hudl.com:8080/eureka/v2"]
