environment: thor
infrastructure:
  web:
    preferences:
      environment_variables:
      - REGISTRATOR_LOG_LEVEL: "DEBUG"
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","-cleanup","-resync","300","eureka://eureka.vpc2.thorhudl.com:8080/eureka/v2"]
    preferences:
      ecsCluster: t-marvel-ecs-vpc2
