environment: testsidecar
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-resync","300","-cleanup","-require-label","eureka://registrator-testing.thorhudl.com:5050/eureka/v2"]
    preferences:
      ecsCluster: t-marvel-ecs-vpc2
      environment_variables:
      - REGISTRATOR_LOG_LEVEL: "DEBUG"