environment: thor
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","eureka://localhost:8080/eureka/v2"]
    preferences:
      ecsCluster: t-marvel-ecs
      environment_variables:
      - foo: bar
