environment: prod
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","-resync","300","eureka://eureka.app.hudl.com:8080/eureka/v2"]
    preferences:
      ecsCluster: p-marvel-ecs
