environment: thor
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","-resync","300","eureka://classic-eureka.vpc.thorhudl.com:8080/eureka/v2"]
    preferences:
      ecsCluster: t-marvel-ecs
