environment: sidecartest
infrastructure:
  web:
    requirements:
      docker_command: ["-ttl","30","-ttl-refresh","15","-require-label","-log","/logs","eureka://registrator-testing.thorhudl.com:8080/eureka/v2", "-log", "/logs"]
    preferences:
      ecsCluster: t-marvel-perftest-orch
