schema: 1.5.5

service:
  name:  registrator
  tribe: foundation
infrastructure:
  web:
    preferences:
      environment_variables:
      - SERVICE_EUREKA_lookup_elbv2_endpoint: "false"
      - SERVICE_REGISTER: "false"
      - REGISTRATOR_LOG_LEVEL: "INFO"
      - FARGO_LOG_LEVEL: "NOTICE"
    requirements:
      cpu_units: 10
      soft_memory_limit: 16
      hard_memory_limit: 64
      networking_mode: host
      docker_labels:
      - is-marvel: "false"
      deployment_options:
        minimum_healthy_percent: 50
        maximum_percent: 100
      #scheduling_strategy: DAEMON
      logging:
        log_driver: sumologic
        log_options:
          - sumo-url: https://collectors.us2.sumologic.com/receiver/v1/http/ZaVnC4dhaV3mk-HkGnFXhZEyMwzk7bLFb3-W4qLeVhpH_cyVQNq970gYuk76CZQN8txlbobpWwslxJErgNGBnS5QIrxrU50-SmXfQ10SfPjcdIvl4ysNlg==
          - sumo-queue-size: "400"
          - sumo-source-name: $environment-$branch-registrator-{{Tag}}
          - sumo-source-host: $environment-{{Tag}}
          - sumo-source-category: app_registrator
      volumes:
      - name: root
        host_path: /
        container_path: /rootfs
        read_only: true
      - name: var_run
        host_path: /var/run
        container_path: /var/run
        read_only: false
      - name: sys
        host_path: /sys
        container_path: /sys
        read_only: true
      - name: var_lib_docker
        host_path: /var/lib/docker/
        container_path: /var/lib/docker/
        read_only: true
      - name: docker_socket
        host_path: /var/run/docker.sock
        container_path: /tmp/docker.sock
        read_only: true
    iam:
      role: $environmentprefix-$service-ecs

build:
    head_commit: $headcommit
    docker_image: $dockerimage
    branch: $branch
    build_number: $buildnumber
