schema: 1.5.1

service:
  name:  registrator
  tribe: foundation
infrastructure:
  web:
    preferences:
      environment_variables:
      - SERVICE_EUREKA_lookup_elbv2_endpoint: "false"
      - SERVICE_REGISTER: "false"
      - REGISTRATOR_LOG_LEVEL: "INFO"
      - FARGO_LOG_LEVEL: "NOTICE"
    requirements:
      cpu_units: 10
      soft_memory_limit: 16
      hard_memory_limit: 64
      networking_mode: host
      docker_labels:
      - is-marvel: "false"
      deployment_options:
        minimum_healthy_percent: 50
        maximum_percent: 100
      scheduling_strategy: DAEMON
      log_paths:
      - sourceCategory: app_registrator
        pathExpression: /var/log/app_registrator/**
        dateFormat: yyyy-MM-dd HH:mm:ss
      volumes:
      - name: log
        host_path: /var/log/app_registrator
        container_path: /logs
        read_only: false
      - name: root
        host_path: /
        container_path: /rootfs
        read_only: true
      - name: var_run
        host_path: /var/run
        container_path: /var/run
        read_only: false
      - name: sys
        host_path: /sys
        container_path: /sys
        read_only: true    
      - name: var_lib_docker
        host_path: /var/lib/docker/
        container_path: /var/lib/docker/
        read_only: true
      - name: docker_socket
        host_path: /var/run/docker.sock
        container_path: /tmp/docker.sock
        read_only: true
    iam:
      role: $environmentprefix-$service-ecs

build:
    head_commit: $headcommit
    docker_image: $dockerimage
    branch: $branch
    build_number: $buildnumber
