schema: 1.1.1

service:
  name:  registrator
  tribe: foundation
infrastructure:
  web:
    requirements:
      cpu_units: 10
      soft_memory_limit: 128
      hard_memory_limit: 256
      log_paths:
      - sourceCategory: app_registrator
        pathExpression: /var/log/app_registrator/**
        dateFormat: yyyy/MM/dd hh24:mi:ss
      volumes:
      - name: log
        host_path: /var/log/app_registrator
        container_path: /logs
        read_only: false
      - name: root
        host_path: /
        container_path: /rootfs
        read_only: false
      - name: var_run
        host_path: /var/run
        container_path: /var/run
        read_only: false
      - name: sys
        host_path: /sys
        container_path: /sys
        read_only: false    
      - name: var_lib_docker
        host_path: /var/lib/docker/
        container_path: /var/lib/docker/
        read_only: false
      - name: docker_socket
        host_path: /var/run/docker.sock
        container_path: /tmp/docker.sock
        read_only: false
      - name: etc_sumo
        host_path: /etc/sumo
        container_path: /etc/sumo
        read_only: false
    iam:
      managed_policies:
        - hudl-webserver-generic
